[build-system]
requires = ["setuptools>=45", "wheel", "cmake>=3.12", "numpy<=1.26.4"]
build-backend = "setuptools.build_meta"

[project]
name = "simpler-whisper"
version = "0.2.2"
authors = [
    {name = "Roy Shilkrot", email = "roy.shil@gmail.com"},
]
description = "A simple Python wrapper for whisper.cpp"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy",
]

[project.urls]
"Homepage" = "https://github.com/locaal-ai/simpler-whisper"
"Bug Tracker" = "https://github.com/locaal-ai/simpler-whisper/issues"

[tool.setuptools]
packages = ["simpler_whisper"]

[tool.setuptools.package-data]
simpler_whisper = ["*.dll", "*.pyd", "*.so", "*.metal"]

[tool.pytest]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"