name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        acceleration: ['cpu', 'cuda']
        exclude:
          - os: macos-latest
            acceleration: cuda
          - os: ubuntu-latest
            acceleration: cuda

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy cmake wheel setuptools build cibuildwheel

    - name: Build wheel
      env:
        CIBW_ENVIRONMENT: "SIMPLER_WHISPER_ACCELERATION='${{ matrix.acceleration }}' MAOSX_DEPLOYMENT_TARGET=10.13"
        CIBW_BUILD: "cp310-* cp311-* cp312-*"
        CIBW_ARCHS_MACOS: "universal2"
        CIBW_ARCHS_WINDOWS: "AMD64"
        CIBW_ARCHS_LINUX: "x86_64"
        CIBW_BUILD_VERBOSITY: 3
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - name: Test import
      if: false
      run: |
        python -c "import sys; sys.path.pop(0); import simpler_whisper; print(simpler_whisper.__file__)"

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        path: |
          wheelhouse/*.whl
